import os
import sys
import pypdf
from groq import Groq


def extract_text_from_pdf(pdf_path):

    if not os.path.exists(pdf_path):
        print(f"\n[!] Couldn't find this file: {pdf_path}")
        print("    Double-check the path and try again.")
        sys.exit(1)

    if not pdf_path.lower().endswith(".pdf"):
        print("\n[!] That doesn't look like a PDF file.")
        print("    Make sure the file name ends with .pdf")
        sys.exit(1)

    print(f"\n[*] Found your resume: {pdf_path}")

    collected_text = ""

    with open(pdf_path, "rb") as file:
        reader = pypdf.PdfReader(file)
        total_pages = len(reader.pages)
        print(f"[*] Pages found: {total_pages}")

        # loop through every page and grab its text
        for i in range(total_pages):
            page = reader.pages[i]
            text = page.extract_text()
            if text:
                collected_text += text + "\n"

    if not collected_text.strip():
        print("\n[!] Couldn't read any text from this PDF.")
        print("    If your resume is a scanned image, this tool won't work on it.")
        print("    Try exporting your resume as a proper text-based PDF.")
        sys.exit(1)

    print(f"[*] Successfully read {len(collected_text)} characters of text.\n")
    return collected_text


def analyse_resume_with_ai(resume_text, api_key):

    client = Groq(api_key=api_key)

    # the prompt tells the AI exactly what kind of feedback we want
    prompt = f"""
You are a senior career coach and resume expert who has helped hundreds of students
and freshers land their first jobs. You give honest but kind feedback.

Read the resume below carefully and give feedback in these 7 sections:

1. OVERALL SCORE (out of 10)
   Score it honestly. Explain in 2 sentences why you gave that score.

2. STRENGTHS
   What has this person done well? List 3 to 5 things.

3. THINGS TO IMPROVE
   What is weak or missing? Be specific — don't just say "make it better", say HOW.

4. MISSING SECTIONS
   Are there sections a recruiter would expect but can't find?
   (e.g. a skills section, a project section, a LinkedIn link, a summary, etc.)

5. FORMATTING & READABILITY
   Is it easy to scan in 10 seconds? Is it too long, too short, cluttered?

6. KEYWORDS
   What important keywords related to their field are present?
   What keywords are missing that would help with ATS (resume-scanning software)?

7. TOP 3 THINGS TO DO RIGHT NOW
   If this person has 30 minutes to improve their resume today, what should they do first?

Keep the tone friendly and encouraging. Use simple language — this person may be a student.

---
RESUME:
{resume_text}
---
"""

    print("[*] Sending your resume to the AI...")
    print("[*] This usually takes 5 to 15 seconds...\n")

    response = client.chat.completions.create(
        messages=[{"role": "user", "content": prompt}],
        model="llama-3.3-70b-versatile",
        temperature=0.7,
        max_tokens=1500,
    )

    return response.choices[0].message.content


def save_to_file(feedback_text, filename="resume_feedback.txt"):

    with open(filename, "w", encoding="utf-8") as f:
        f.write("=" * 60 + "\n")
        f.write("          AI RESUME ANALYSIS REPORT\n")
        f.write("=" * 60 + "\n\n")
        f.write(feedback_text)
        f.write("\n\n" + "=" * 60 + "\n")
        f.write("         Generated by AI Resume Analyser\n")
        f.write("=" * 60 + "\n")

    print(f"\n[*] Feedback saved! Open this file to read it: {filename}")


def main():

    print("\n" + "=" * 60)
    print("        AI Resume Analyser")
    print("        Powered by Groq + LLaMA 3 (free)")
    print("=" * 60)

    print("\nPaste the full path to your resume PDF below.")
    print("Example: C:\\Users\\You\\Documents\\my_resume.pdf\n")
    pdf_path = input("Resume path: ").strip().strip('"').strip("'")

    print("\n" + "-" * 60)
    print("You need a FREE Groq API key to use this.")
    print("If you don't have one yet:")
    print("  1. Go to https://console.groq.com")
    print("  2. Sign up (it's free, no credit card)")
    print("  3. Go to API Keys and create one")
    print("-" * 60 + "\n")

    # check if the key is already saved as an environment variable
    api_key = os.environ.get("GROQ_API_KEY")

    if api_key:
        print("[*] Found a Groq API key saved on this machine. Using that.")
    else:
        api_key = input("Paste your Groq API key: ").strip()

    if not api_key:
        print("\n[!] No API key entered. Can't continue without one.")
        sys.exit(1)

    print()

    resume_text = extract_text_from_pdf(pdf_path)
    feedback = analyse_resume_with_ai(resume_text, api_key)

    print("=" * 60)
    print("           HERE'S YOUR RESUME FEEDBACK")
    print("=" * 60 + "\n")
    print(feedback)

    print("\n" + "-" * 60)
    save = input("Save this feedback to a text file? (yes / no): ").strip().lower()

    if save in ["yes", "y"]:
        save_to_file(feedback)
    else:
        print("[*] No problem — feedback not saved.")

    print("\nGood luck with your applications!")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()